ktor:
    application:
        modules:
            - com.azlaan95.ApplicationKt.module
    deployment:
        port: 8081
    db:
        config:
            url: ""
            user: ""
            password: ""